server:
  port: 8888
#eureka:
#  client:
#    # 由于是作为服务端角色，所以不需要获取服务端，改为false，默认为true
#    fetchRegistry: false
#    # 暂时不需要将自己也注册到Eureka
#    registerWithEureka: false
#    # 将Eureka服务端指向自己
#    serviceUrl:
#      defaultZone: http://localhost:8888/eureka/

spring:
  application:
    name: eurekaserver
eureka:
  instance:
    # 由于不支持多个localhost的Eureka服务器，但是又只有本地测试环境，所以就只能自定义主机名称了
    # 主机名称改为eureka01
    hostname: eureka02
  client:
    fetch-registry: false
    # 去掉register-with-eureka选项，让Eureka服务器自己注册到其他Eureka服务器，这样才能互相启用
    service-url:
      # 注意这里填写其他Eureka服务器的地址，不用写自己的
      defaultZone: http://eureka01:8801/eureka/