server:
  port: 8888
eureka:
  client:
    # 由于是作为服务端角色，所以不需要获取服务端，改为false，默认为true
    fetchRegistry: false
    # 暂时不需要将自己也注册到Eureka
    registerWithEureka: false
    # 将Eureka服务端指向自己
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/